sudo: false
language: python
python:
- '2.7'
addons:
  apt:
    packages:
    - pandoc
before_install:
- pip install --upgrade pip
- pip install --upgrade setuptools
- pip install --upgrade pytest
- pip --version
install:
- python setup.py -q install
- python setup.py sdist
script:
- python setup.py test
- pip install -r requirements/dev.txt
- py.test
- coverage xml
- python-codacy-coverage -r coverage.xml
deploy:
  provider: releases
  api_key:
    secure: jRh/1cgeplMywOkLHfH5nJv3LCPfKCwGUmkdoy/ygHSXcnUCwroFe4LhsHF35+Assc+csL88WNTWpy5t9wPVCNW2+/vvHSErd62+hKQP6ZwGXRwBeyF6cCnYUrg38x0abCKyNPJX28jaLD/wc0s1kzmbuH6dmiE5d/DU2z0SwGWQjN8yYqTNBelBQIp7tVkYFxDgR+TzYa4W/TvGLMuBxDbDTnOuQeeFxGA6UA+V6SLZ4MJwjq1Im74SZZx/V8tV+y/BUIC3MuFRDsPJPTUrekYFhPcuTorlbbBznGc15MmHsYVupno0qAAv44uCs/2UNyS1ITWTSB+5WVoyZD/Or6xTjUtR1Pa5UYksKOuI8CkTOjn/nj3Q/hAcjvNL+GZK7P2VdyWPTaKZ9tCTyvg+dDk0qQlYzKUcLmJMubciH9oACanxKo/8w5b5kaK2td28EPot8ZTnhEjygdVqGNxVNaSqxal034X4L174Ili/2wjnNC7Q5byWBj1+8Jw/mRzJ/yxSXluKoczn3EFsbV3IYBOoX6etF7wPMNhwYavbV9i3DEkTfh2TPCoyi6BNSEheCZZtJfCIoaDlnBJmh2Gz0mrJphp8giXANOdhzHPyQ96yUjCXGpKYnnN0gq+jQHwk6Yh++WVC5FpPCYe88ud2EOIQtZ8GLJuqOMHfTXMhQ7A=
  file: dist/*.tar.gz
  on:
    tags: true
    repo: halkeye/ac-flask
env:
  global:
    secure: dCgPOgVthE6eWJi3vjo0Kq4tXf8cCfRDXE7st5dsbPNfpuE6Qb/QRyeAnc4bFBrIu1HpUu1058hmt+AUa0RMcjD1IGQZI4vaziVAykTpKi20RFIfkShxlC2ZNNQyNlcWlsX1MWuyMy7Z6lhDJMmxho+Fu4FYneiM6hTWYmJwjl8q4u09YvMNc4ftuxuR9KTmdqqAnPqHcmVlU3suaXkUd10oz0OUIy2Dap7U/Rvn9sjphHtEr77QrFbM+euFUTO6HIqRZ/5eeqwydGjwHikAyPIQnisc4rF8QUJrjFc7rGlc788HF3IZ7pk3FLg0y1YCsK5wpe8LNnSmZTte+2GthuZuUS+9uuDMFvrZvbg81yLQ2Sc2m4opomIrCJotIFfUi35X24Hp2cJ2sDlHhVvQ4iwWqy5QAOaYr+xzcyAPsHw6WwLRznclraSOrHfFTRRtZ8BLqXRRvwOt/DJFu4WQlEmPn/UTTZ/HsVpLHfV+L+W8xk13F/X68Ch2E+IQBjYre5xAN+55n8CZ4ju4BbstJxO+mHm9eGvReLejglT/vUNNBm/vE9sWXCPM57Qfu8MG22GV9tLLYOULu4owhQBpjcqmWS+iJyXam2CJc2vL5WSwfxbieY79JCNy0Sh+2jJ4kqmC5SXoXjciFyfREF//cRx2Ess28sjjbbs/1c0w7oU=
