sudo: false
language: python
python:
- '2.7'
addons:
  apt:
    packages:
    - pandoc
before_install:
- pip install --upgrade pip
- pip install --upgrade setuptools
- pip install --upgrade pytest
- pip --version
install:
- python setup.py -q install
- python setup.py sdist
script:
- python setup.py test
- pip install -r requirements/dev.txt
- py.test
- coverage xml
- python-codacy-coverage -r coverage.xml
env:
  global:
    secure: uhs5gT3M3Awtz0uleYLFt75nLs2K+Mp9oMsits2S56GYnv6+4DQqDpc4sFP4RWW/57JLOD3EHRNL8eni4c2f1tHppVpsD2Oxf/IyLYhInbKdBETKEOOgb1eVHIo00ZUe9C+sCI3YRaYDKjSJHJ4SmEpGSZ9qPiHlSDKoI4m+87YNOgy9hV+cUUnHMKKytwXyhQiXnNSwURY6A1mxSweyGG52QvdHxqMbrXER8MllPhZlzirBOhiRJblSvLbcJmvtixGAiMS/rDpvyxMd4bYgz9rVLD2jbBvWYqsaOw2qJUDHRTM4uX5kaDVQWXrIu2WnULW1OenT6QsGMinH07dJ+LGH5nsoXTpw5Ace8jsHNHY2SEUwf5ie+eFHJJNQEA6kKKX1glFP9xOcLeVpP+/n/qUwguHJbzKpsDdOLyOLcgZfWlmb4+YCaKyaoWAVmnLR7wkOVi7vmnXNZTl6AsSfdJPnVeFT3ZQhkh2pxKrbj0V5XqCAqaBMBoStNym4UNzjjxr/8UdBTqC15uGEgC+3gEoN7srYP8HCbMfml27lt0PkkPJznT+tv1bzqmJNfTe/3u6bIK31Us5Z4NzC4pYM7oLcDQOvoSNfniwl5Bz9ShyLp7DtV+VGTMc4LIlIXjkuEEeXZd1aAgPWF4n9Bm7MMAF8ZTRM0z5haDq3XIvP96I=
